name: Devious Client CI/CD

on:
  push:
    branches: [master, main, development, experimental]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Assemble
        run: ./gradlew assemble --console=plain
      - name: Build
        run: ./gradlew build --stacktrace -x test -x checkstyleMain --console=plain
      - name: Bootstrap
        if: github.event_name == 'push'
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            ./gradlew bootstrapStable -x test -x checkstyleMain --console=plain
          elif [ "$GITHUB_REF" = "refs/heads/development" ]; then
            ./gradlew bootstrapSnapshot -x test -x checkstyleMain --console=plain
          elif [ "$GITHUB_REF" = "refs/heads/experimental" ]; then
            ./gradlew bootstrapExperimental -x test -x checkstyleMain --console=plain
          fi
      - name: Push to hosting
        if: github.event_name == 'push'
        run: |
          git clone https://github.com/melxin/devious-hosting.git
          cp -r ./runelite-client/build/bootstrap/. ./devious-hosting
          cd devious-hosting
          git config --global user.email "melxin@tutamail.com"
          git config --global user.name "Github Actions"
          git add -A
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            msg='Auto release - Client (Stable)'
          elif [ "$GITHUB_REF" = "refs/heads/development" ]; then
            msg='Auto release - Client (Snapshot)'
          else
            msg='Auto release - Client (Experimental)'
          fi
          git commit -m "$msg"
          git push https://melxin:${{ secrets.REPO_PAT }}@github.com/melxin/devious-hosting.git master

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Checkstyle
        run: ./gradlew checkstyleMain --console=plain
