name: Devious Client Build

on:
  push:
    branches: [master, main, development, experimental]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          arguments: >-
            build --stacktrace -x checkstyleMain -x checkstyleTest -x pmdMain -x pmdTest --console=plain

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gradle
        with:
          arguments: checkstyleMain --console=plain
