name: Gradle CI

on:
  push:
    branches: [master, main, development, experimental]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      tasks: build --stacktrace -x test -x checkstyleMain -x checkstyleTest

  checkstyle:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      tasks: checkstyleMain
