name: Devious Client CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      tasks: build --stacktrace -x test -x checkstyleMain -x checkstyleTest

  checkstyle:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      tasks: checkstyleMain
